apiVersion: certmanager.k8s.io/v1alpha
kind: ClusterIssuer
metadata: 
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'hitchjme@gmail.com'
    privateKeySecretRef: 
      name: letsencrypt-prod
    http01: {}